---

- hosts: all
  become: true
  tasks:

  - name: remove apache2 package
    apt:
      name: apache2
      state: absent
    when: ansible_distribution == "Debian"

  - name: remove php support for apache
    apt:
     name: libapache2-mod-php
     state: absent
    when: ansible_distribution == "Debian"

  - name: remove apache2 package
    yum:
      name: httpd
      state: absent
    when: ansible_distribution == "CentOS"

  - name: remove php support for apache
    yum:
     name: php
     state: absent
    when: ansible_distribution == "CentOS"
