---
 
- hosts: all
  become: true
  pre_tasks:

   - name: Install updates CentOS
     tags: always
     yum:
       update_only: yes
       update_cache: yes
     when: ansible_distribution == "CentOS"
      
   - name: Install updates Debian
     tags: always
     apt:
       upgrade: dist
       update_cache: yes
     when: ansible_distribution == "Debian"

- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php for Deb servers
    tags: apache,apache2,debian
    apt:
       name:
         - apache2
         - libapache2-mod-php
       state: latest
       update_cache: yes
    when: ansible_distribution == "Debian"
 
  - name: install apache and php for CentOS servers
    tags: apache,centos,httpd
    yum:
       name:
         - httpd
         - php
       state: latest
       update_cache: yes
    when: ansible_distribution == "CentOS"

- hosts: db_servers
  become: true
  tasks:
  
  - name: install mariadb package
    tags: centos,db,mariadb
    yum: 
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"
   
  - name: install mariadb package
    tags: debian,db,mariadb
    apt: 
      name: mariadb
      state: latest
    when: ansible_distribution == "Debian"

- hosts: file_servers
  become: true
  tasks:
  
  - name: Install samba package
    tags: samba
    package:
      name: samba
      state: latest 
