---
 
- hosts: all
  become: true
  pre_tasks:

   - name: Update cache CentOS
     tags: always
     yum:
       update_cache: yes
     changed_when: false
     when: ansible_distribution == "CentOS"
      
   - name: Update cache Debian
     tags: always
     apt:
       update_cache: yes
     changed_when: false
     when: ansible_distribution == "Debian"

   - name: Copy sources list file
     tags: debian
     copy:
       src: sources.list
       dest: /etc/apt/sources.list
       owner: root
       group: root
       mode: 0644
     when: ansible_distribution == "Debian"

- hosts: all
  become: true
  tasks:

  - name: Add ssh key for simone
    tags: always
    authorized_key:
      user: simone
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIscf4J86xMJb8z+IU6ij7uxso/2Nmdvr8UCxVsn49iy ansible" 

- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php for Deb servers
    tags: apache,apache2,debian
    apt:
       name:
         - apache2
         - libapache2-mod-php
       state: latest
       update_cache: yes
    when: ansible_distribution == "Debian"
 
  - name: install apache and php for CentOS servers
    tags: apache,centos,httpd
    yum:
       name:
         - httpd
         - php
       state: latest
       update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: Start httpd service (CentOS)
    tags: apache,apache2,httpd
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "CentOS"

  - name: Change e-mail address for admin
    tags: apache,centos,httpd
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin somebody@somewhere.net
    when: ansible_distribution == "CentOS"
    register: httpd

  - name: Restart httpd (CentOS)
    tags: apache,centos,httpd
    service:
      name: httpd
      state: restarted
    when: httpd.changed

  - name: Copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks:
  
  - name: install mariadb package
    tags: centos,db,mariadb
    yum: 
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"
   
  - name: install mariadb package
    tags: debian,db,mariadb
    apt: 
      name: mariadb
      state: latest
    when: ansible_distribution == "Debian"

- hosts: file_servers
  become: true
  tasks:
  
  - name: Install samba package
    tags: samba
    package:
      name: samba
      state: latest 
